version: '3.1'

services:

  db:
    image: postgres
    restart: always

    environment:
      - POSTGRES_DB=sic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
